name: drake colcon ws

on:
  push:

jobs:
  build_testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: rolling
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: drake
          target-ros2-distro: rolling
          skip-tests: true
          # Remove cmake-target after https://github.com/RobotLocomotion/ros-drake-vendor/issues/10
          colcon-defaults: |
            {
              "build": {
                "cmake-target": "install",
                "merge-install": true
              }
            }
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: RobotLocomotion/drake-external-examples
          ref: main
          path: ros_ws/src
      - name: build tests
        shell: bash
        working-directory: ros_ws
        run: |
          # gflags is required by drake_cmake_installed
          sudo apt-get update && sudo apt-get install -y libgflags-dev
          . /opt/ros/rolling/setup.bash
          . install/setup.bash
          colcon build --merge-install --packages-select drake_cmake_installed drake_ament_cmake_installed --event-handlers console_direct+
